### ISSUE TITLE
Important delay while pushing notifications and other operations from server to device

### ISSUE THREAD

**Issue by ghassen1khalil** [wso2-attic/product-emm#179]
Hi WSO2 Team,

I am working on your WSO2EMM solution and more specifically the Android agent. 

What I noticed when dealing with this part is some delay while sending notifications and other operations from the server to the device. Here I need to mention that I am using "Local Polling" and not "GCM".

Is there any recommendation to resolve this issue please guys ?

**Comment by Kamidu** [comment]
While using "Local Polling" the delay which appears when the operations getting applied to the device is due to polling interval. In Android platform configurations under Platform configurations, You can find Polling Interval configuration. You can change that to the minimum level of 1 second.

**Comment by ghassen1khalil** [comment]
Yes that's what I did but the problem persists ! Operations are sent from the server and they are not even received by the device in most of the cases. 
On the operations log page it keeps on showing "wating" status.
