### ISSUE TITLE
Android source of wso2 emm-agent-android-master 

### ISSUE THREAD

**Issue by xin4428** [wso2-attic/product-emm#209]
Hello ,everyone !Who has the Android source of wso2 emm-agent-android-master ?that API_VERSION is 2。Can you sent one to my email ?xin2840830311@gmail.com
   thank you

**Comment by milanperera** [comment]
Android agent's source code (for EMM 2.0.0 upwards) can be found in https://github.com/wso2/product-emm/tree/master/modules/mobile-agents/android/client

**Comment by xin4428** [comment]
But source code  in https://github.com/wso2/product-emm/tree/master/modules/mobile-agents/android/client is not an Android source code, can not be used as a project to import

**Comment by xin4428** [comment]
But the source code in https://github.com/wso2/product-emm/tree/master/modules/mobile-agents/android/client is not an Android source code, can not be used as a project to import,
Do you have the Android source code?

**Comment by milanperera** [comment]
That is the android source code we use. You can import this source from
Android Studio without any issue.

On Fri, Apr 29, 2016 at 10:26 AM, xin4428 <notifications@github.com> wrote:

> But the source code in
> https://github.com/wso2/product-emm/tree/master/modules/mobile-agents/android/client
> is not an Android source code, can not be used as a project to import,
> Do you have the Android source code?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/wso2/product-emm/issues/209#issuecomment-215626887>
>



-- 
*Milan Perera *| Software Engineer
WSO2, Inc | lean. enterprise. middleware.
#20, Palm Grove, Colombo 03, Sri Lanka
Mobile: +94 77 309 7088 | Work: +94 11 214 5345
Email: milan@wso2.com <aruna@wso2.com> | Web: www.wso2.com
<http://lk.linkedin.com/in/milanharinduperera>

**Comment by inoshperera** [comment]
This is a graddle build project. You need to use Android studio to import
it. Please refer here[1]

[1].
https://github.com/wso2/product-emm/blob/master/modules/mobile-agents/android/client/README.md

Inosh Perera,
Software Engineer, WSO2 Inc.
email: inoshp@wso2.com
tel: 0785293686

**Comment by xin4428** [comment]
thank you ! Can I use Eclipse  open that source ?

**Comment by boxidilshan** [comment]
The official IDE for Android is Idea now. Better go with that.

**Comment by milanperera** [comment]
I dont think you will be able to open that source from Eclipse, because it
uses different builder plugin (ant) to build the android projects
and the folder structure of the project is also different.

I think it is better if you use Android Studio for the Android Development
since Google has stopped supporting Eclipse (ADT plugin).


On Fri, Apr 29, 2016 at 10:38 AM, xin4428 <notifications@github.com> wrote:

> thank you ! Can I use Eclipse open that source ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/wso2/product-emm/issues/209#issuecomment-215628080>
>



-- 
*Milan Perera *| Software Engineer
WSO2, Inc | lean. enterprise. middleware.
#20, Palm Grove, Colombo 03, Sri Lanka
Mobile: +94 77 309 7088 | Work: +94 11 214 5345
Email: milan@wso2.com <aruna@wso2.com> | Web: www.wso2.com
<http://lk.linkedin.com/in/milanharinduperera>

**Comment by xin4428** [comment]
Thank you

**Comment by paru0000** [comment]
Hi 
xin4428
How did you solve your problem of opening the project in studio,please provide me step by step instruction

**Comment by milanperera** [comment]
Please follow the instructions of below link.
https://github.com/wso2/product-emm/blob/master/modules/mobile-agents/android/client/README.md
