### ISSUE TITLE
Downloading APK From Store

### ISSUE THREAD

**Issue by vivekellappan** [wso2-attic/product-emm#236]
When I click install from store i got notification installing but it is not static. Keep on downloading in progress. App is not installing

**Comment by hasuniea** [comment]
Could you able to check the operation log of the EMM console.
Does INSTALL_APPLICATION operation is still in pending status.

**Comment by vivekebics** [comment]
Yes..It is pending status

**Comment by hasuniea** [comment]
Did you check the behavior of other operations like device lock,ring.Even
they are also in pending status,If you put some lock/ring operation.

On Mon, Jun 13, 2016 at 3:15 PM, Vivek <notifications@github.com> wrote:

> Yes..It is pending status
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/wso2/product-emm/issues/236#issuecomment-225535545>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMZQyqcJb3QeGLYP6Yvkw5gzcWATKNsKks5qLSbHgaJpZM4I0EtM>
> .
>



-- 
*Hasunie Adikari*
Software Engineer
WSO2 Inc.; http://wso2.com
lean.enterprise.middleware
blog http://hasuniea.blogspot.com
Mobile:+94715139495

**Comment by vivekebics** [comment]
I get notification. INSTALL_APPLICATION status changed to completed. But i have not got apk file. It is just show downloading progress alone also notification is also not constant.

**Comment by hasuniea** [comment]
Could you able to provide the EMM version which you use.?

On Mon, Jun 13, 2016 at 3:40 PM, Vivek <notifications@github.com> wrote:

> I get notification. INSTALL_APPLICATION status changed to completed. But i
> have not got apk file. It is just show downloading progress alone also
> notification is also not constant.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/wso2/product-emm/issues/236#issuecomment-225540930>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMZQykjAKCvkRcQMYkoY6kuNCknzORZ4ks5qLSyCgaJpZM4I0EtM>
> .
>



-- 
*Hasunie Adikari*
Software Engineer
WSO2 Inc.; http://wso2.com
lean.enterprise.middleware
blog http://hasuniea.blogspot.com
Mobile:+94715139495

**Comment by vivekebics** [comment]
We are using EMM Verion 2.1.0

**Comment by gnakale** [comment]
@ghost what's the size of your apk file ?
