### ISSUE TITLE
Can't get authentication right (android)

### ISSUE THREAD

**Issue by TripwireNL** [wso2-attic/product-emm#242]
Hi,

I've installed the EMM on my test server and i'm using HTTPS. I've installed everything needed and followed the guide to install EMM on my Server. I can get into the console which is working fine. What I however can't get working for some time now is the Authentication. I've followed the steps to generate the BKS file (Android) with the default password and added it to my Client-client/Res/Raw directory. I've also changed the Server_Port in the Constants.java class to 9443. I'm running the server in DEBUG mode and keep getting the error message on the server:

> http-nio-9443-exec-2, READ: TLSv1.2 Alert, length = 2
> http-nio-9443-exec-2, RECV TLSv1.2 ALERT:  fatal, certificate_unknown
> http-nio-9443-exec-2, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
> http-nio-9443-exec-2, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
> http-nio-9443-exec-2, called closeOutbound()
> http-nio-9443-exec-2, closeOutboundInternal()
> http-nio-9443-exec-2, SEND TLSv1.2 ALERT:  warning, description = close_notify
> http-nio-9443-exec-2, WRITE: TLSv1.2 Alert, length = 2

Any idea how I can get this working?

**Comment by MayukhaC** [comment]
any luck with this? please let me know

**Comment by Tripwire999** [comment]
@MayukhaC nope still isn't working. We let it slide for now since we don't have the time and resources to get this fixed.

**Comment by kasundananjaya** [comment]
Hi @Tripwire999,

Looks like your BKS is not properly generated. If you have installed your self signed SSL cert to WSO2 EMM server, you should have a .pem file which you used in that process right? Use the same to generate the BKS (Read: http://callistaenterprise.se/blogg/teknik/2011/11/24/creating-self-signed-certificates-for-use-on-android/). And then replace your existing BKS file with the new one generated using above method.

Thanks
