### ISSUE TITLE
Issue facing in End-user Registering an Android Device via the Managed Profile.

### ISSUE THREAD

**Issue by PraveenJP** [wso2-attic/product-emm#307]
I have followed the WSO2 EMM 2.1.0 Documentation for managed profile https://docs.wso2.com/display/EMM210/End-user+Registering+an+Android+Device+via+the+Managed+Profile - please refer the link. First five steps are easily going after uninstalled the WSO2 Agent. I stuck with 6th step. then how i reinstall the gent app again? please instruct me.

**Comment by kasundananjaya** [comment]
You don't need to install the app again. If steps 1-5 are correctly done, you should see the agent application automatically installed onto your work profile (see this screenshot : https://docs.wso2.com/display/EMM210/End-user+Registering+an+Android+Device+via+the+Managed+Profile?preview=/50520859/51252254/Work-Place-Applications.png). You should launch that in this 6th step.
