### ISSUE TITLE
fatal exception when trying to silentInstallApp

### ISSUE THREAD

**Issue by kelleyduran** [wso2-attic/product-emm#357]
We have been testing a solution to silent install an app, and keep seeing this error appear in the logcat. 

The WSO2 Agent App, and the WSO2 EMM System Service are signed by vendor with firmware signing key, the device is a COPE device, and the application we are trying to silent install is not signed by vender firmware signing key- as we thought that was the way it should be by following documentation. 

The APK seems to build fine- why we're getting the  java.lang.NoClassDefFoundError is confusing.
```EMM agent has sent a command with operation code: SILENT_INSTALL_APPLICATION command:
W/dalvikvm( 2353): Unable to resolve superclass of Lorg/wso2/emm/system/service/utils/AppUtils$1; (31)
W/dalvikvm( 2353): Link of class 'Lorg/wso2/emm/system/service/utils/AppUtils$1;' failed
E/dalvikvm( 2353): Could not find class 'org.wso2.emm.system.service.utils.AppUtils$1', referenced from method org.wso2.emm.system.service.utils.AppUtils.silentInstallApp
W/dalvikvm( 2353): VFY: unable to resolve new-instance 1967 (Lorg/wso2/emm/system/service/utils/AppUtils$1;) in Lorg/wso2/emm/system/service/utils/AppUtils;
D/dalvikvm( 2353): VFY: replacing opcode 0x22 at 0x0004
W/dalvikvm( 2353): Unable to resolve superclass of Lorg/wso2/emm/system/service/utils/AppUtils$1; (31)
W/dalvikvm( 2353): Link of class 'Lorg/wso2/emm/system/service/utils/AppUtils$1;' failed
D/dalvikvm( 2353): DexOpt: unable to opt direct call 0x3c3b at 0x06 in Lorg/wso2/emm/system/service/utils/AppUtils;.silentInstallApp
W/dalvikvm( 2353): threadid=10: thread exiting with uncaught exception (group=0x41840ba8)
E/AndroidRuntime( 2353): FATAL EXCEPTION: IntentService[EMMSystemService]
E/AndroidRuntime( 2353): Process: org.wso2.emm.system.service, PID: 2353
E/AndroidRuntime( 2353): java.lang.NoClassDefFoundError: org.wso2.emm.system.service.utils.AppUtils$1
E/AndroidRuntime( 2353): 	at org.wso2.emm.system.service.utils.AppUtils.silentInstallApp(AppUtils.java:57)
E/AndroidRuntime( 2353): 	at org.wso2.emm.system.service.EMMSystemService.silentInstallApp(EMMSystemService.java:608)
E/AndroidRuntime( 2353): 	at org.wso2.emm.system.service.EMMSystemService.doTask(EMMSystemService.java:280)
E/AndroidRuntime( 2353): 	at org.wso2.emm.system.service.EMMSystemService.onHandleIntent(EMMSystemService.java:158)
E/AndroidRuntime( 2353): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime( 2353): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2353): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2353): 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/Process ( 2353): Sending signal. PID: 2353 SIG: 9
I/ActivityManager(  522): Process org.wso2.emm.system.service (pid 2353) has died.
D/ActivityManager(  522): send app_CRASH broadcast, packageName:org.wso2.emm.system.service
W/ContextImpl(  522): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1162 com.android.server.am.ActivityManagerService.onVideoPlayerCrashed:3715 com.android.server.am.ActivityManagerService.handleAppDiedLocked:3745 com.android.server.am.ActivityManagerService.appDiedLocked:3883 com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied:1046```

**Comment by likebrain** [comment]
We have the same Problem on Android 4.4.2.
I´m not realy familiar with Android and Java but I debug a little bit around this Problem.

I think here is a Problem with the "Hidden API / Internal API" which is used to Install the App.
` java.lang.NoClassDefFoundError: org.wso2.emm.system.service.utils.AppUtils$1`

In the AppUtils.java Class on line 57
` PackageInstallObserver observer = new PackageInstallObserver()`

This Class is inside the HiddenAPI but not in Android 4.4.2 Hidden API
The Package-Namespace of this Class is  => android.app

But in the Android 4.4.2 Repository is no PackageInstallObserver Class.
https://github.com/android/platform_frameworks_base/tree/android-sdk-4.4.2_r1.0.1/core/java/android/app/

In Android Lollipop the class can be found in this Namespace.
https://github.com/android/platform_frameworks_base/blob/lollipop-release/core/java/android/app/PackageInstallObserver.java

I think its a Compatibility Problem between the SDK´s / API´s.

**Comment by likebrain** [comment]
In Android 4.4.2 we must use the PackageManager Class to do this.

https://github.com/android/platform_frameworks_base/blob/android-cts-4.4_r4/core/java/android/content/pm/PackageManager.java

Here is the working implementation:
https://github.com/paulononaka/Android-InstallInBackgroundSample/blob/master/app/src/main/java/com/github/paulononaka/installapkinbackground/apihelper/ApplicationManager.java#L302

I'll implement this in a fork this fallback should be thrown this exception

**Comment by kelleyduran** [comment]
Looks like we are both attempting to do the same thing. I replaced the use of  android.app.PackageInstallObserver with android.content.pm.IPackageInstallObserver;  I'll report back if the fix I put in works at this fork: https://github.com/kelleyduran/product-emm

**Comment by likebrain** [comment]
Thank you for share this Solution!
It works great on my 4.4.2 Test-Device!
I can cleanly Install and Uninstall Apps.

I do not understand why this was so badly implemented...
In the Agent application the abstraction is very beautifully done.

https://github.com/wso2/product-emm/tree/master/modules/mobile-agents/android/client/client/src/main/java/org/wso2/emm/agent/services/operation

I also see chances for more compatibility and features here....
For example it is possible to Hide / Unhide apps via the PolicyManager...

http://stackoverflow.com/questions/19114439/android-hide-unhide-app-icon-programmatically

But it's just not implemented
https://github.com/wso2/product-emm/blob/master/modules/mobile-agents/android/client/client/src/main/java/org/wso2/emm/agent/services/operation/OperationManagerOlderSdk.java#L511

**Comment by MayukhaC** [comment]
Hi @kelleyduran  Could you please be of any help for #376 issue. Thank you.
