### ISSUE TITLE
getLegacyExternalStorageDirectory cannot be resolved

### ISSUE THREAD

**Issue by paru0000** [wso2-attic/product-emm#360]
When i open the project in studio i m getting the following error in logcat
C:\Users\parvathi\Desktop\ClientEMM\client\client\src\main\java\org\wso2\emm\agent\api\RuntimeInfo.java
Error:(159, 38) error: cannot find symbol method getLegacyExternalStorageDirectory()
C:\Users\parvathi\Desktop\ClientEMM\client\client\src\main\java\org\wso2\emm\agent\services\AlarmReceiver.java
Error:(56, 36) error: cannot find symbol method getExtra(String)
C:\Users\parvathi\Desktop\ClientEMM\client\client\src\main\java\org\wso2\emm\agent\services\NetworkConnectedReceiver.java
Error:(42, 28) error: cannot find symbol method startServiceAsUser(Intent,UserHandle)
C:\Users\parvathi\Desktop\ClientEMM\client\client\src\main\java\org\wso2\emm\agent\utils\CommonUtils.java
Error:(432, 11) error: cannot find symbol method startServiceAsUser(Intent,UserHandle)
Error:(445, 11) error: cannot find symbol method startServiceAsUser(Intent,UserHandle)

Please help me solve the issue

**Comment by MayukhaC** [comment]
I know its too late.
The solution is to build the android.jar from the AOSP or you could use the .jar files form this [repository](https://github.com/anggrayudi/android-hidden-api)
For reference: https://stackoverflow.com/a/40559229/8000126

**Comment by kasundananjaya** [comment]
Hi @paru0000, This seems to be a little different than what @MayukhaC suggested. His suggestion is definitely the solution if you get a class not found etc exception when you build the system service application. But Android Agent does not contain hidden APIs. 

In that case, the issue @paru0000 having seems to me like her Android SDK path is not properly configured. May I get a better context to this issue?

Thanks
