### ISSUE TITLE
Android Agent

### ISSUE THREAD

**Issue by atakmdm** [wso2-attic/product-emm#363]
So, I have everything setup per the instruction in the documentation but when I try to enroll a device, it just spins on Authenticating Please Wait and never does anything else. I have https port 9443 enabled. I have tried the admin account and received the same result. I also tried using fake creds and still got the same result.

**Comment by atakmdm** [comment]
This is the log from Android Studio Monitor, and nothing shows in the server log: 

01-28 16:46:08.355 27659-27659/? E/Zygote: v2
01-28 16:46:08.355 27659-27659/? I/libpersona: KNOX_SDCARD checking this for 10269
01-28 16:46:08.355 27659-27659/? I/libpersona: KNOX_SDCARD not a persona
01-28 16:46:08.355 27659-27659/? W/SELinux: Function: selinux_compare_spd_ram, index[1], priority [2], priority version is VE=SEPF_SECMOBILE_6.0.1_0029
01-28 16:46:08.355 27659-27659/? E/Zygote: accessInfo : 0
01-28 16:46:08.355 27659-27659/? W/SELinux: SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=org.wso2.emm.agent 
01-28 16:46:08.355 27659-27659/? I/art: Late-enabling -Xcheck:jni
01-28 16:46:08.385 27659-27659/? D/TimaKeyStoreProvider: TimaSignature is unavailable
01-28 16:46:08.385 27659-27659/? D/ActivityThread: Added TimaKeyStore provider
01-28 16:46:08.395 27659-27662/? I/art: Debugger is no longer active
01-28 16:46:08.415 27659-27659/? W/ResourcesManager: getTopLevelResources: /data/app/org.wso2.emm.agent-1/base.apk / 1.0 running in org.wso2.emm.agent rsrc of package org.wso2.emm.agent
01-28 16:46:08.425 27659-27659/? I/InjectionManager: Inside getClassLibPath + mLibMap{0=, 1=}
01-28 16:46:08.425 27659-27659/? D/ResourcesManager: For user 0 new overlays fetched Null
01-28 16:46:08.425 27659-27659/? I/InjectionManager: Inside getClassLibPath caller 
01-28 16:46:08.435 27659-27659/? W/System: ClassLoader referenced unknown path: /data/app/org.wso2.emm.agent-1/lib/arm64
01-28 16:46:08.475 27659-27659/? D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
01-28 16:46:08.475 27659-27659/? D/FirebaseApp: Initialized class com.google.firebase.iid.FirebaseInstanceId.
01-28 16:46:08.485 27659-27659/? D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
01-28 16:46:08.485 27659-27659/? I/FA: App measurement is starting up, version: 9080
01-28 16:46:08.495 27659-27659/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
01-28 16:46:08.495 27659-27659/? D/FA: Debug logging enabled
01-28 16:46:08.495 27659-27659/? D/FA: AppMeasurement singleton hash: 28290227
01-28 16:46:08.495 27659-27659/? W/ResourcesManager: getTopLevelResources: /data/app/org.wso2.emm.agent-1/base.apk / 1.0 running in org.wso2.emm.agent rsrc of package org.wso2.emm.agent
01-28 16:46:08.505 27659-27675/? W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/org.wso2.emm.agent/shared_prefs/com.google.android.gms.measurement.prefs.xml.bak
01-28 16:46:08.515 27659-27659/? D/FirebaseApp: Initialized class com.google.android.gms.measurement.AppMeasurement.
01-28 16:46:08.515 27659-27659/? I/FirebaseInitProvider: FirebaseApp initialization successful
01-28 16:46:08.515 27659-27659/? D/InjectionManager: InjectionManager
01-28 16:46:08.515 27659-27659/? D/InjectionManager: fillFeatureStoreMap org.wso2.emm.agent
01-28 16:46:08.515 27659-27659/? I/InjectionManager: Constructor org.wso2.emm.agent, Feature store :{}
01-28 16:46:08.515 27659-27659/? I/InjectionManager: featureStore :{}
01-28 16:46:08.515 27659-27659/? W/ResourcesManager: getTopLevelResources: /data/app/org.wso2.emm.agent-1/base.apk / 1.0 running in org.wso2.emm.agent rsrc of package org.wso2.emm.agent
01-28 16:46:08.525 27659-27659/? D/ContextRelationManager: ContextRelationManager() : FEATURE_ENABLED=true
01-28 16:46:08.525 27659-27659/? D/RelationGraph: garbageCollect()
01-28 16:46:08.585 27659-27659/? I/Timeline: Timeline: Activity_launch_request id:org.wso2.emm.agent time:225821952
01-28 16:46:08.645 27659-27659/? D/Activity: performCreate Call Injection manager
01-28 16:46:08.645 27659-27659/? I/InjectionManager: dispatchOnViewCreated > Target : org.wso2.emm.agent.AgentReceptionActivity isFragment :false
01-28 16:46:08.655 27659-27659/? D/SecWifiDisplayUtil: Metadata value : SecSettings2
01-28 16:46:08.655 27659-27659/? D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{c6e1dcc I.ED..... R.....I. 0,0-0,0}
01-28 16:46:08.665 27659-27682/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-28 16:46:08.695 27659-27659/? E/ViewSystem: ViewRootImpl #2 Surface is not valid.
01-28 16:46:08.695 27659-27659/? W/ResourcesManager: getTopLevelResources: /data/app/org.wso2.emm.agent-1/base.apk / 1.0 running in org.wso2.emm.agent rsrc of package org.wso2.emm.agent
01-28 16:46:08.695 27659-27659/? D/RelationGraph: garbageCollect()
01-28 16:46:08.755 27659-27659/? W/ProcessManager: waitpid on failed exec failed: No child processes
01-28 16:46:08.755 27659-27659/? E/org.wso2.emm.agent.api.ShellExecutor: Root check shell command processing failed. The device is not rooted.
01-28 16:46:08.755 27659-27659/? D/Activity: performCreate Call Injection manager
01-28 16:46:08.755 27659-27659/? I/InjectionManager: dispatchOnViewCreated > Target : org.wso2.emm.agent.ServerDetails isFragment :false
01-28 16:46:08.755 27659-27659/? D/SecWifiDisplayUtil: Metadata value : SecSettings2
01-28 16:46:08.755 27659-27659/? D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{a03e1d7 I.ED..... R.....I. 0,0-0,0}
01-28 16:46:08.775 27659-27682/? I/Adreno: QUALCOMM build                   : 69d1fb1, If3b409a3da
                                           Build Date                       : 06/08/16
                                           OpenGL ES Shader Compiler Version: XE031.08.00.02
                                           Local Branch                     : 
                                           Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.HB.1.1.1.C1.06.00.00.165.183
                                           Remote Branch                    : NONE
                                           Reconstruct Branch               : NOTHING
01-28 16:46:08.785 27659-27682/? D/libEGL: eglInitialize EGLDisplay = 0x7f7cc1f188
01-28 16:46:08.785 27659-27682/? I/OpenGLRenderer: Initialized EGL, version 1.4
01-28 16:46:08.815 27659-27676/? D/FA: Connected to remote service
01-28 16:46:08.815 27659-27659/? W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:08.815 27659-27659/? W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:08.815 27659-27682/? D/libGLESv1: DTS_GLAPI : DTS is not allowed for Package : org.wso2.emm.agent
01-28 16:46:09.025 27659-27659/? D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
01-28 16:46:09.045 27659-27659/? W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:09.055 27659-27659/? I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@6af1d56 time:225822421
01-28 16:46:09.055 27659-27659/? I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@432ef88 time:225822422
01-28 16:46:09.055 27659-27676/? W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/org.wso2.emm.agent/shared_prefs/com.google.android.gms.appid.xml.bak
01-28 16:46:12.955 27659-27659/org.wso2.emm.agent I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@6af1d56 time:225826320
01-28 16:46:13.365 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-28 16:46:13.405 27659-28150/org.wso2.emm.agent W/InstanceID/Rpc: Found 10016
01-28 16:46:13.495 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-28 16:46:14.045 27659-27659/org.wso2.emm.agent D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 1128) or=1
01-28 16:46:14.205 27659-28150/org.wso2.emm.agent D/org.wso2.emm.agent.InstanceIDListenerService: Refreshed token received.
01-28 16:46:14.415 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:15.155 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:15.445 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:15.815 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:16.655 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:16.685 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:16.925 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:17.455 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:17.825 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:17.865 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:18.165 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:18.905 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:18.925 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:19.025 27659-27676/org.wso2.emm.agent I/FA: Tag Manager is not found and thus will not be used
01-28 16:46:19.025 27659-27676/org.wso2.emm.agent D/FA: Logging event (FE): _s, Bundle[{_o=auto}]
01-28 16:46:19.035 27659-27676/org.wso2.emm.agent D/FA: Connected to remote service
01-28 16:46:19.155 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:19.185 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:19.415 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:19.935 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:22.635 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processKey 1
01-28 16:46:23.705 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:23.715 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:24.295 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:24.325 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:24.995 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:25.165 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:25.435 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:25.835 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-28 16:46:25.945 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-28 16:46:26.015 27659-27659/org.wso2.emm.agent D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{82c5eab V.E...... R.....I. 0,0-0,0}
01-28 16:46:26.085 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:26.115 27659-27659/org.wso2.emm.agent D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
01-28 16:46:26.895 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-28 16:46:27.015 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-28 16:46:27.025 27659-27659/org.wso2.emm.agent W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/org.wso2.emm.agent/shared_prefs/org.wso2.emm.agent.xml.bak
01-28 16:46:27.035 27659-27659/org.wso2.emm.agent I/Timeline: Timeline: Activity_launch_request id:org.wso2.emm.agent time:225840408
01-28 16:46:27.075 27659-27659/org.wso2.emm.agent D/ViewRootImpl: #3 mView = null
01-28 16:46:27.085 27659-27659/org.wso2.emm.agent E/ViewRootImpl: sendUserActionEvent() mView == null
01-28 16:46:27.085 27659-27659/org.wso2.emm.agent W/ResourcesManager: getTopLevelResources: /data/app/org.wso2.emm.agent-1/base.apk / 1.0 running in org.wso2.emm.agent rsrc of package org.wso2.emm.agent
01-28 16:46:27.095 27659-27659/org.wso2.emm.agent D/RelationGraph: garbageCollect()
01-28 16:46:27.145 27659-27659/org.wso2.emm.agent D/Activity: performCreate Call Injection manager
01-28 16:46:27.145 27659-27659/org.wso2.emm.agent I/InjectionManager: dispatchOnViewCreated > Target : org.wso2.emm.agent.AuthenticationActivity isFragment :false
01-28 16:46:27.155 27659-27659/org.wso2.emm.agent D/SecWifiDisplayUtil: Metadata value : SecSettings2
01-28 16:46:27.155 27659-27659/org.wso2.emm.agent D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{b87c9b9 I.E...... R.....ID 0,0-0,0}
01-28 16:46:27.205 27659-27659/org.wso2.emm.agent I/InjectionManager: dispatchCreateOptionsMenu :org.wso2.emm.agent.AuthenticationActivity
01-28 16:46:27.205 27659-27659/org.wso2.emm.agent I/InjectionManager: dispatchPrepareOptionsMenu :org.wso2.emm.agent.AuthenticationActivity
01-28 16:46:27.215 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:27.245 27659-27659/org.wso2.emm.agent D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
01-28 16:46:27.285 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:27.285 27659-27659/org.wso2.emm.agent D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 1128) or=1
01-28 16:46:27.315 27659-27659/org.wso2.emm.agent I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3e80f80 time:225840687
01-28 16:46:28.325 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-28 16:46:28.445 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-28 16:46:30.365 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:31.275 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:31.795 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:32.235 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:32.485 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:32.935 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-28 16:46:33.065 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-28 16:46:33.085 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:33.275 27659-27659/org.wso2.emm.agent D/ViewRootImpl: MSG_RESIZED: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 1000) or=1
01-28 16:46:33.295 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:34.035 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processKey 0
01-28 16:46:34.225 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processKey 1
01-28 16:46:34.505 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:34.775 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:34.995 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:36.065 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:36.515 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:36.835 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:37.005 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processKey 1
01-28 16:46:37.755 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:38.515 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:39.005 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-28 16:46:39.165 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-28 16:46:39.235 27659-27659/org.wso2.emm.agent D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{fd2d2a5 V.E...... R.....I. 0,0-0,0}
01-28 16:46:39.315 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:39.335 27659-27659/org.wso2.emm.agent D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
01-28 16:46:40.025 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:40.205 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 0
01-28 16:46:40.305 27659-27659/org.wso2.emm.agent D/ViewRootImpl: ViewPostImeInputStage processPointer 1
01-28 16:46:40.335 27659-27659/org.wso2.emm.agent D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{7890ad2 V.E...... R.....I. 0,0-0,0}
01-28 16:46:40.435 27659-29023/org.wso2.emm.agent W/ActivityThread: ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
01-28 16:46:40.435 27659-29023/org.wso2.emm.agent I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-28 16:46:40.435 27659-29023/org.wso2.emm.agent I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
01-28 16:46:40.455 27659-27659/org.wso2.emm.agent D/ViewRootImpl: #3 mView = null
01-28 16:46:40.515 27659-27659/org.wso2.emm.agent W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
01-28 16:46:40.545 27659-27659/org.wso2.emm.agent D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
01-28 16:46:40.555 27659-27659/org.wso2.emm.agent E/ViewRootImpl: sendUserActionEvent() mView == null
01-28 16:46:40.685 27659-27659/org.wso2.emm.agent D/DynamicClientManager: com.android.volley.NoConnectionError: javax.net.ssl.SSLPeerUnverifiedException: Hostname 12.97.28.184 not verified:
                                                                              certificate: sha1/lQtnhYQjWrSXMU0o4ZSJa4Ax4fs=
                                                                              DN: 1.2.840.113549.1.9.1=#16116174616b6d646d40676d61696c2e636f6d,CN=12.97.28.184,OU=EMM,O=ATAK,L=Washington,ST=District of Columbia,C=US
                                                                              subjectAltNames: []

**Comment by rasika** [comment]
Could you let us know the product version you are using?
