### ISSUE TITLE
Installing EMM Agent in IOS Device

### ISSUE THREAD

**Issue by Tanmayj0424** [wso2-attic/product-emm#375]
Hi There,

     I am trying to install EMM Agent from IOS Device it display pop up message saying cannot connect to specific ip address. Also when trying to skip agent it shows error code 500 while logging in with use and password.
     Does anyone here knows solution to this issue have been through document lot many times but not getting where the problem is.

Thanks Tanmay

**Comment by madawas** [comment]
@Tanmayj0424

**Comment by madawas** [comment]
@Tanmayj0424 what EMM version are you using and what configuration changes have you done?

**Comment by Tanmayj0424** [comment]
Thanks For the Reply, the version i am using is  WSO2 EMM 2.2.0 i have updated certain xml file as per mentioned in documentation.  Also in one place /repository/deployment/server
/jaggeryapps/emm-web-agent/config there is edit mentioned in document to edit confi.json file which is not there at mentioned place.  I think this might be the problem area.  But i am awaiting a workable solution. I know carbon logs but dont know server Logs.  Installing EMM Agent displays token-handler.js.

Thanks Madawas.

**Comment by rasika** [comment]
@Tanmayj0424 Can you share with us the  carbon logs with us. Are you trying the EMM server on a remote instance or in your local machine?

**Comment by Tanmayj0424** [comment]
Hi Rasika,
     We have hosted it on linux server and the carbon logs file size is 19 Mb if you can skype me on the same id would be simple enough to communicate and would lead to faster resoultion.
Carbon Logs:-
https://drive.google.com/open?id=0B6mLcVHFGoNNSG1wWlVWTGJjODg
Thank You For Your Time & Assistance.
Thanks Tanmay.

**Comment by madawas** [comment]
@Tanmayj0424 I have noticed the following exception when analysing the provided logs. 
```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: No trusted certificate found
```
Seems like this has occurred due to a missing configuration step.
Have you followed all the steps provided in the [Documentation](https://docs.wso2.com/display/EMM220/iOS+Configurations)

**Comment by Tanmayj0424** [comment]
@madawas will check as per Documentation and if help needed will get back to you.

Thanks Tanmay.
