### ISSUE TITLE
Emm Agent app from product emm modules never authenticate

### ISSUE THREAD

**Issue by MayukhaC** [wso2-attic/product-emm#378]
I enter the server address and the credentials but cannot login. The pop up scren says 'Please wait Authenticating' and never authenticates.

The below are the logs from logcat. Please let me know how to authenticate. I think its evident that the last line is the culprit. But how do I overcome it? Thank you

    06-05 09:12:47.556 11783-11783/? I/InstantRun: starting instant run server: is main process
    06-05 09:12:47.614 11783-11783/? V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
    06-05 09:12:47.615 11783-11783/? V/BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
    06-05 09:12:47.615 11783-11783/? V/BoostFramework: mAcquireTouchFunc method= public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
    06-05 09:12:47.617 11783-11783/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b1910b0
    06-05 09:12:47.617 11783-11783/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@4e1eb29
    06-05 09:12:47.677 11783-11854/? I/Adreno: QUALCOMM build : fa96243, I96480c87c9
                                           Build Date     :     09/24/16
                                           OpenGL ES Shader Compiler Version: XE031.09.00.03
                                           Local Branch                     : 
                                           Remote Branch                    : 
                                           Remote Branch                    : 
                                           Reconstruct Branch               : 
    06-05 09:12:47.681 11783-11854/? I/OpenGLRenderer: Initialized EGL, version 1.4
    06-05 09:12:47.682 11783-11854/? D/OpenGLRenderer: Swap behavior 1
    06-05 09:12:47.791 11783-11783/? I/Timeline: Timeline: Activity_idle id: 
    android.os.BinderProxy@e11a80a time:25836740
    06-05 09:12:48.119 11783-11783/? D/org.wso2.emm.agent.events.listeners.ApplicationStateListener: {"packageName":"org.wso2.emm.agent","state":"removed"}
    06-05 09:12:48.962 11783-11783/org.wso2.emm.agent D/org.wso2.emm.agent.events.listeners.ApplicationStateListener: {"packageName":"org.wso2.emm.agent","state":"upgraded"}
    06-05 09:12:57.714 11783-11821/org.wso2.emm.agent W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
    06-05 09:13:45.247 11783-11783/org.wso2.emm.agent I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@e11a80a time:25894196
    06-05 09:13:46.419 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@cccd64b
    06-05 09:13:46.551 11783-11783/org.wso2.emm.agent I/Timeline: Timeline: 
    Activity_launch_request id:org.wso2.emm.agent time:25895499
    06-05 09:13:46.615 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@eaee372
    06-05 09:13:46.615 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@5efc3c3
    06-05 09:13:46.638 11783-11783/org.wso2.emm.agent E/org.wso2.emm.agent.api.ShellExecutor: Root check shell command processing failed. The device is not rooted.
    06-05 09:13:46.693 11783-11783/org.wso2.emm.agent I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@e3f1941 time:25895642
    06-05 09:13:46.705 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:13:46.705 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:13:55.187 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:13:55.188 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:13:56.256 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:13:56.256 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:13:58.390 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:13:58.390 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:13:58.405 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:13:58.405 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:14:01.494 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@23babe2
    06-05 09:14:01.494 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@4933b73
    06-05 09:14:02.218 11783-11783/org.wso2.emm.agent I/Timeline: Timeline: Activity_launch_request id:org.wso2.emm.agent time:25911167
    06-05 09:14:02.381 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@a6196bf
    06-05 09:14:02.382 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@e35918c
    06-05 09:14:02.404 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@5aaad89
    06-05 09:14:02.404 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@b81d18e
    06-05 09:14:02.602 11783-11783/org.wso2.emm.agent W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
    06-05 09:14:02.613 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:14:02.613 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:14:02.614 11783-11783/org.wso2.emm.agent I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@4ff5b1d time:25911563
    06-05 09:14:02.614 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:14:02.614 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:14:09.797 11783-11783/org.wso2.emm.agent W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
    06-05 09:14:09.799 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:14:09.799 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:14:09.811 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:14:09.811 11783-11783/org.wso2.emm.agent E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    06-05 09:14:12.145 11783-11783/org.wso2.emm.agent W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
    06-05 09:14:16.984 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@9fe6229
    06-05 09:14:16.984 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@7ee79ae
    06-05 09:14:17.595 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2ccaf12
    06-05 09:14:17.595 11783-11783/org.wso2.emm.agent V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@86a36e3
    06-05 09:14:17.706 11783-13528/org.wso2.emm.agent D/NetworkSecurityConfig: No Network Security Config specified, using platform default
    06-05 09:14:17.842 11783-11783/org.wso2.emm.agent D/DynamicClientManager: com.android.volley.NoConnectionError: javax.net.ssl.SSLHandshakeException: Handshake failed`

**Comment by kasundananjaya** [comment]
Seems like the app tries to connect via HTTPS. Have you properly installed the BKS file which is generated using your SSL certificate.? https://docs.wso2.com/display/EMM201/Generating+a+BKS+File+for+Android

**Comment by MayukhaC** [comment]
@kasundananjaya  I have installed the BKS file as given in the same document you mentioned. Configured the Constats.java files in Client Application. But still the same issue persists. I have also given the right IP adress x.y.z.a while creating the SSL certificate. You can have a look at the list of all the Keys I have created [here](https://drive.google.com/drive/folders/0B3rKGZrcxYM5Nm0tdXZ0YVhXc3c?usp=sharing) . Please help me resolve this.Thank you

**Comment by kasundananjaya** [comment]
Your files looks OK to me. There must be some mismatch between the certs. Which version of EMM/IoT are you using? If it's the latest, can you carefully follow these steps (https://docs.wso2.com/display/IoTS300/Configuring+Android+for+HTTPS+Communication) from the scratch and see if it works? If not, please share full ADB Logcat when you're trying to enroll.

**Comment by MayukhaC** [comment]
I was using the wso2emm-2.2.0 and followed the guide you have provided and i got a log almost similar to this question log. So, on your advice I installed Wso2 IoT server and launched the source codes form wso2-cdmf-agent-android onto the device without changing the bks file. I wanted to just check what would the issue. Got the issues due to android.jar. Resolved them and everything worked fine. I didnt even change the BKS file. That was a clean install and registration to the server also went smooth. So, we need not change the BKS file ?

**Comment by kasundananjaya** [comment]
Default application communicates using HTTP. You have to change the BKS if you are using HTTPS. Just trace the requests(using an app like Packet capture) to see if the working solution uses HTTPS. Have you used openssl to generate the self signed certificate? If so, if must be a V3 certificate.

**Comment by MayukhaC** [comment]
Yeah, I tried with a V3 certificate. and the packet capture says it is HTTP. for now I am continuing with the HTTP and will worry about this later.

**Comment by MayukhaC** [comment]
@kasundananjaya No luck yet. I have changed the openssl.cnf file to make a change to v3 certificate as suggested in the document.

For the Iot server I have tried with https: port as 8243 and got the below errors:

client side error:
`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

server side exception:

    [2017-06-22 11:56:19,314] [IoT-Core] ERROR - SourceHandler I/O error: Received fatal alert: certificate_unknown
    javax.net.ssl.SSLException: Received fatal alert: certificate_unknown	
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:245)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:280)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:410)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:119)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	at java.lang.Thread.run(Thread.java:748) 

I have created a bks in the same way as the documentation.

On execution of ` openssl s_client -connect localhost:9443`
resulted in

    CONNECTED(00000003)
    depth=0 C = xxxx, ST = xxxx, L = xxxx, O = xxxx, OU = xxxx, CN = <localhost ip given>, emailAddress =xxxx
    verify error:num=18:self signed certificate
    verify return:1
    depth=0 C = xxxx, ST = xxxx, L = xxxx, O =xxxx, OU = xxxx, CN = xxxx emailAddress = xxxx
    verify return:1
    ---
    Certificate chain
     0 s:/C=xxxx/ST=xxxx/L=xxxx/O=xxxx/OU=xxxx/CN=<localhost ip given>/emailAddress=xxxx
       i:/C=xxxx/ST=xxxx/L=xxxx/O=xxxx/OU=IT/CN=<localhost ip given>/emailAddress=xxxx
    ---
    Server certificate
    -----BEGIN CERTIFICATE-----
    MIIFrzCCA5cCBAKkVfcwDQYJKoZIhvcNAQELBQAwgZsxCzAJBgNVBAYTAlVTMRMw
    EQYDVQQIDApDYWxpZm9ybmlhMREwDwYDVQQHDAhTYW4gSm9zZTEOMAwGA1UECgwF
    QWRhcmExCzAJBgNVBAsMAklUMRQwEgYDVQQDDAsxMC4xMC4xLjExOTExMC8GCSqG
     SIb3DQEJARYibWF5dWtoYV9jaGVla2F0aUBhZGFyYW5ldHdvcmtzLmNvbTAeFw0x
    NzA2MjIxNzA1MTBaFw0xOTA2MjIxNzA1MTBaMIGbMQswCQYDVQQGEwJVUzETMBEG
    A1UECAwKQ2FsaWZvcm5pYTERMA8GA1UEBwwIU2FuIEpvc2UxDjAMBgNVBAoMBUFk
    YXJhMQswCQYDVQQLDAJJVDEUMBIGA1UEAwwLMTAuMTAuMS4xMTkxMTAvBgkqhkiG
    9w0BCQEWIm1heXVraGFfY2hlZWthdGlAYWRhcmFuZXR3b3Jrcy5jb20wggIiMA0G
    CSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCyWj7OLJZxTNHxJStfp1orr9sPQbuA
    gB26ZCJ+V8YOFmWfRiN1lK9poBk0/H6Klw2JDI8QUaUIfc9IxcpWZO5I6ZXgf7k4
    o4vzltUXDoaR8qRlmmf25JOvlT1AB4nVt0+RC3btRvGr9lUWfobSwLib9CKCNufT
    8pFgsVD1qGK1lM2HTRz76ttDwNJMRTCSKF0j0nLZkPENhaZ//whc0/FpxwatGqTj
    yn7Q/bzu414b+nC1aAOV+NpInCxzeEH/YJM0J/2gxxzSg7+M0KyzgIMZk9iP/TB5
    6sompavBWW9RJmXfweSjHBLeBr6kS5UBLLK8nAfIsXRj+LBKyXLIS6xMdC0wTRth
    TVDO7UOMm2RT2VbKqYRb9uvdOXyavDUw/wsrmb20EfWYCt6yrcbHwfZgGkCSpS/g
    OJ7ooFuTs112uvi0GYGHJU7Zd9uaVqHqeyn90ZN+QkWMfondncJ9aot4SnqlBr3F
    OxYxjXDSulhPe4zMeZ3PERjM+SI53piKWnE8j5TdIn5o9u1Dx46LuBZ2+Nlbszh0
    R1Z4I7giKugBx9gahs46amGMi7sUlQqyFvJiqkVd0CxFhnCwQtIlIcvrssg8gjs3
    JWsPl/42KHpYULax4rcmFUlOKY2rs5SaaCx1lXhi8xd6rQB0VW6ILiY1UODKxkmT
    NIUY82pB5UcIfwIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQBe82MjUMoIJJzvNgc9
    9VTJ81J2xB3aJV3+MJF5uB4IJpp6gvVL/dNcWyvIqT82bxnuYCsekpP/zKKbBBwK
    PEOTRqW05668vlqnqsksihMPbO2Id6AvKeKWB3LtHu0vP5NgJUwoUBBxycLz/gc3
    EyA5/Ncsz7DLzClMimTZ+oVQ4Pe2QndLfw16QxCfj1N0O4kaalQ9Tv7xMrbHXb8r
    GJLnqy6FsEDc6x9jbEjgNS3sM+wpJr0JPltr8pf5F1MDEnUQj65qIz6l/+J/GM2I
    DA7qeC+MO6eUR7bnw82zcmTOkJzUlYwJzg6Zo1poYk1QOMJfAjga0LFQPXRWbY7o
    a/SNqujfX7u9AyOTsdKleVua7owE7gykPBMmH/wdRwCOMm4FK6wPtx3inD/MrUbR
    s7sm1kOzUbhg/6c7aqktZPcHd3fjHeZ3E0S4lXYM20wVjlBBw5gMmlA3Qw2lEB05
    9ucvSJ1K4WBHAEVbVv6dntvtQgwolZJ5kEG58VXVamdgkRPYuo3Vo2Tmzh+cUx0R
    ws8Ed9EcBwZSg0fBKnFsjbyh4epwaf3ubEmDwQh3/mYj24WEr3iGKihxmxB5TSKX
    tE62ZplviyxaFyzZ8llEXDUur5Kpp6vkRgSdBrg4s+2C9E8vXgBm3qROtldJrx7M
    XxlexxHKuLJV2+tWBIhM0M7twg==
    -----END CERTIFICATE-----
    subject=/C=xxxx/ST=xxxx/L=xxxx/O=xxxx/OU=xxxx/CN=<localhost ip given>/emailAddress=xxxx
    issuer=/C=xxxx/ST=xxxx/L=xxxx/O=xxxx/OU=xxxx/CN=<localhost ip given>/emailAddress=xxxx
    No client certificate CA names sent
    Peer signing digest: SHA512
    Server Temp Key: ECDH, P-256, 256 bits
    ---
    SSL handshake has read 2199 bytes and written 433 bytes
    ---
    New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
    Server public key is 4096 bit
    Secure Renegotiation IS supported
    Compression: NONE
    Expansion: NONE
    No ALPN negotiated
    SSL-Session:
        Protocol  : TLSv1.2
        Cipher    : ECDHE-RSA-AES256-GCM-SHA384
        Session-ID: 594C1015B346FB6C5C7C99A5F5A1A382DF442B0D4F7380A1BB760E32AC195789
        Session-ID-ctx: 
        Master-Key:5BCAEC31B7F1D4C2AB2CC6509D79E5F8EA1989519A3BB058DDF3999D19A288E96F3625B7E6BA
    238319681EEA354258C8
        Key-Arg   : None
        PSK identity: None
        PSK identity hint: None
        SRP username: None
        Start Time: 1498157077
        Timeout   : 300 (sec)
        Verify return code: 18 (self signed certificate)
    ---
    read:errno=0

How do i trust the self-signed certificate to the server?

**Comment by kasundananjaya** [comment]
You can do that. I have configured my local machine following the steps mentioned in above link I shared (carefully following step  "Generating a BKS File [and all steps when you expand this drop down section"]) and it all worked fine. Can you try BKS generating using [1] or [2]?

[1] - https://github.com/GaryLaurenceau/generate-keystore-bks
[2] - http://callistaenterprise.se/blogg/teknik/2011/11/24/creating-self-signed-certificates-for-use-on-android/
