### ISSUE TITLE
silent uninstall

### ISSUE THREAD

**Issue by MayukhaC** [wso2-attic/product-emm#384]
Uninstall of Enterprise apps not working!

**Comment by ikerfah** [comment]
System Services must be signed and installed on your device.

**Comment by MayukhaC** [comment]
Silent uninstall working on Andorid 6.0. But not working on Android 7.0. 

This might be probably due to the behaviour changes in Android 7.0 as stated below. 
 
    DELETE_PACKAGES
    String DELETE_PACKAGES
    Allows an application to delete packages.
    Not for use by third-party applications.
    Starting in N, user confirmation is requested when the application deleting the package is not the same application that installed the package.
    Constant Value: "android.permission.D ELETE_PACKAGES" `
