### ISSUE TITLE
Does MDM provide an abstraction layer API for push notifications to simplify app development?

### ISSUE THREAD

**Issue by kaiyuan01** [wso2-attic/product-emm#44]
Hi,

We are very interested in WSO2 MDM and considering migrate HP Anywhere to WSO2. Does WSO2 provide an abstraction layer for push notifications for app developers, in other words, how do I migrate existing apps in production to WSO2 with minimal code change in push notification?

In a nutshell, does WSPO2 provide a simple API to simplfy app developers to implement push notifications pretty much the same as HP Anywhere can do here:

HP Anywhere:

http://docs.hpanywhere.com/wp-content/uploads/10.12/HP_Anywhere_Online_Help/Default.htm#Best_Practices/Push_Notifications.htm
http://docs.hpanywhere.com/wp-content/uploads/10.12/HP_Anywhere_API_Reference/webframe.html#Simple_Push.html

Thank you.
Jeff

**Comment by kaiyuan01** [comment]
Any replies/updates?

**Comment by prabathabey** [comment]
We do intend to provide support for pluggable push notification mechanisms in the next major version of the product, which is planned for early next year. Stay tuned to architecture@wso2.org or dev@wso2.org for more information on the design/implementation details of all planned features including the one in question.
